apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gridsync-carbon-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: gridsync.rules
    rules:
    - alert: DirtyRegionActive
      expr: count(kube_pod_info{namespace="virginia-dirty"}) > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Workloads running in dirty grid!"
        description: "There are pods actively running in the high-carbon Virginia region. Scheduler should migrate these."
